### ISSUE TITLE
✏ Typos out and about

### ISSUE THREAD

**Issue by jordinerae** [leeandher/leander.xyz#38]
On the notes -> docker page, "blatently" should be spelled "blatantly"
Same for the react 101 page

**Comment by jordinerae** [comment]
On the notes -> learn node page, it should say "if anything **is** confusing"

**Comment by jordinerae** [comment]
> On the notes -> learn node page, it should say "if anything **is** confusing"

just kidding the word is actually missing on all of the notes pages

**Comment by jordinerae** [comment]
On the notes -> react 101 page, put a colon instead of a comma ("Please Note:" instead of "Please Note,"

**Comment by leeandher** [comment]
Should be taken care of in 4d8edc1
