### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by Utsharga** [leeandher/leander.xyz#98]
**Describe the bug**
The image of you on the resume page is stretched beyond 100%.

**To Reproduce**
1. Go to 'https://www.leander.xyz/resume'
2. See error

**Expected behavior**
See the full image of the person with proportional height to width.

**Screenshots**
![image](https://user-images.githubusercontent.com/46984418/116439831-f7cf2d80-a81d-11eb-8a9e-befb34ce44b9.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 90.0.4430.93 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leeandher** [comment]
Thanks for letting me know 👍 fixed it recently
